add docker job

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -125,8 +125,7 @@ jobs:
           AWS_REGION: 'us-east-1'
           SOURCE_DIR: reports-${{ github.sha }}
           DEST_DIR: reports/${{ github.sha }}  
-
-            
+   
   docker:  
     permissions:
       contents: read
@@ -164,20 +163,41 @@ jobs:
             ghcr.io/shadyyasser2003/solar-system:${{ github.sha }}
 
       - name: Docker Image Test
+        env:
+          MONGO_URI: ${{ secrets.MONGO_URI }}
+          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
+          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
         run: |
-          docker images
+          echo "🚀 Starting container for testing..."
+      
           docker run --name solar-system-app -d \
-          -p 3000:3000 \
-          -e MONGO_URI=$MONGO_URI \
-          -e MONGO_USERNAME=$MONGO_USERNAME \
-          -e MONGO_PASSWORD=$MONGO_PASSWORD \
-          ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
-
-          # export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
-          # echo $IP
-
-          # echo Testing Image URL using wget
-          # wget -q -O - 127.0.0.1:3000/live | grep live    
+            -p 3000:3000 \
+            -e MONGO_URI=$MONGO_URI \
+            -e MONGO_USERNAME=$MONGO_USERNAME \
+            -e MONGO_PASSWORD=$MONGO_PASSWORD \
+            ${{ secrets.DOCKER_HUB_USERNAME }}/solar-system-world:${{ github.sha }}
+      
+          echo "⏳ Waiting for app to be healthy..."
+          for i in {1..10}; do
+            if curl -s http://127.0.0.1:3000/live | grep -q "live"; then
+              echo "✅ App is healthy and responded correctly"
+              break
+            fi
+            echo "Waiting... ($i/10)"
+            sleep 3
+          done
+      
+          # لو التطبيق مفعلش نفسه
+          if ! curl -s http://127.0.0.1:3000/live | grep -q "live"; then
+            echo "❌ App failed health check"
+            docker logs solar-system-app
+            exit 1
+          fi
+      
+          echo "🧹 Cleaning up..."
+          docker stop solar-system-app
+          docker rm solar-system-app
+      
 
   dev-deploy:
     name: dev Deployment
@@ -214,7 +234,6 @@ jobs:
           echo "Testing on $URL"
           curl -sS "http://$URL:32000/live" | jq -r '.status' | grep -i live   
 
-
   prod-deploy:
     name: prod Deployment 
     needs: docker
@@ -227,8 +246,7 @@ jobs:
     with:
       MONGO_URL: ${{ vars.MONGO_URL }}
       kubernates-manifest-path: kubernetes/production/
-      environment: production 
-      
+      environment: production    
 
   prod-integration-testing:
         if: github.ref == 'refs/heads/main'
